language: swift
osx_image: xcode9.3
git:
  submodules: false
xcode_project: GpxLocationManager.xcodeproj
xcode_scheme: GpxLocationManager
before_install:
  - brew update
script:
  - xcodebuild -scheme Demo -quiet -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' build
  - xcodebuild -scheme GpxLocationManager -quiet -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' build
  - xcodebuild -scheme GpxLocationManagerTests -quiet -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' test