language: swift
osx_image: xcode9.3
git:
  submodules: false
xcode_project: GpxLocationManager.xcodeproj
xcode_scheme: GpxLocationManager
before_install:
  - brew update
script:
  - ./scripts/build.sh Demo
  - ./scripts/build.sh GpxLocationManager
  - ./scripts/test.sh GpxLocationManagerTests